theme = tokyonight_moon
  # theme = GruvboxDark

  # Lettertype
font_family      Hack Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11

# Transparantie
background_opacity 0.55
background_blur    40

# Window decorations
hide_window_decorations yes
# Of voor specifieke titelbalk controle:
# window_titlebar none

# Custom shaders (uitgecommentarieerd)
# shader /home/chris/bloom.glsl
# shader /home/chris/crt.glsl

